name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies'
                run: npm install

            -   name: 'Run Build'
                run: npx tsc

            -   name: 'Deploy to DigitalOcean'
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DIGITALOCEAN_IP }}
                    username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
                    key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
                    script: |
                        ssh ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_IP }} 
                        rsync -avz --delete dist/** package.json package-lock.json ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_IP }}:/var/www/html/api.floreriaenvios.com &&
                        ssh ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_IP }} "cd /var/www/html/api.floreriaenvios.com && npm install && pm2 stop api.floreriaenvios.com && pm2 start server.js --name api.floreriaenvios.com -o out.log -e error.log"


