name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies & Build'
                run: |
                    npm install
                    npx tsc

            -   name: Deploy to DigitalOcean
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DIGITALOCEAN_HOST }}
                    username: ${{ secrets.DIGITALOCEAN_USERNAME }}
                    key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
                    port: ${{ secrets.DIGITALOCEAN_PORT }}
                    script: |
                        ssh ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} -p ${{ secrets.DIGITALOCEAN_PORT }}