name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies'
                run: npm install

            -   name: 'Run Build'
                run: npx tsc




