name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies & Build'
                run: |
                    npm install
                    npx tsc

            -   name: 'Copy files via SSH'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sshpass -p "$DIGITALOCEAN_PASSWORD" rsync -avz --exclude='*' --include='dist/***' --include='package.json' --include='package-lock.json' --prune-empty-dirs . $DIGITALOCEAN_USERNAME@$DIGITALOCEAN_HOST:/var/www/html/api.floreriaenvios.com

            -   name: 'Install dependencies on server'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sshpass -p "$DIGITALOCEAN_PASSWORD" ssh $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "cd /var/www/html/api.floreriaenvios.com && npm install"

            -   name: 'Restart application PM2'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sshpass -p "$DIGITALOCEAN_PASSWORD" ssh $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "cd /var/www/html/api.floreriaenvios.com && pm2 stop api.floreriaenvios.com && pm2 start server.js --name api.floreriaenvios.com -o out.log -e error.log"