name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies'
                run: npm install

            -   name: 'Run Build'
                run: npx tsc

            -   name: 'Copy files via SSH'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_IP }}
                    DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_SSH_USER }}
                    SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
                run: |
                    ssh $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "mkdir -p /var/www/html/api.floreriaenvios.com"
                    rsync -avz --delete dist/** package.json package-lock.json ssh $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST:/var/www/html/api.floreriaenvios.com


            -   name: 'Install dependencies on server'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_IP }}
                    DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_SSH_USER }}
                run: |
                    ssh -o StrictHostKeyChecking=no $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "cd /var/www/html/api.floreriaenvios.com && npm install"

            -   name: 'Restart application'
                run: |
                    ssh $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "cd /var/www/html/api.floreriaenvios.com && pm2 stop api.floreriaenvios.com && pm2 start server.js --name api.floreriaenvios.com -o out.log -e error.log"