name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies'
                run: npm install

            -   name: 'Run Build'
                run: npx tsc

            -   name: 'Deploy to DigitalOcean'
                uses: appleboy/ssh-action@master
                run: echo "Hello, world!"
                with:
                    host: ${{ secrets.DIGITALOCEAN_IP }}
                    username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
                    key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
                    script: |
                        rsync -avz --delete dist/** files images package.json package-lock.json ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_IP }}:/var/www/html/api.floreriaenvios.com
                        cd /var/www/html/api.floreriaenvios.com                        
                        npm install  # Instala las dependencias en tu servidor
                        pm2 stop
                        pm2 start server.js --name api.floreriaenvios.com -o out.log -e error.log # Reinicia tu aplicación, asumiendo que usas pm2


