name: Deploy to Digital Ocean (jeak-dev-testing)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 'Checkout Code'
                uses: actions/checkout@v4
            -   name: 'Setup Node'
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: 'Install Dependencies'
                run: npm install

            -   name: 'Run Build'
                run: npx tsc

            -   name: 'Copy files via SSH'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_USER }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sudo apt-get install -y sshpass
                    sshpass -p "$DIGITALOCEAN_PASSWORD" ssh -o StrictHostKeyChecking=no $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "mkdir -p /var/www/api.floreriaenvios.com"
                    sshpass -p "$DIGITALOCEAN_PASSWORD" rsync -avz --exclude node_modules --exclude .git . $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST:/var/www/api.floreriaenvios.com

            -   name: 'Install dependencies on server'
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_USER }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sshpass -p "$DIGITALOCEAN_PASSWORD" ssh -o StrictHostKeyChecking=no $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST "cd /var/www/api.floreriaenvios.com && npm install"

            -   name: Restart application
                env:
                    DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
                    DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_USER }}
                    DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
                run: |
                    sshpass -p "$DIGITALOCEAN_PASSWORD" ssh -o StrictHostKeyChecking=no $DIGITALOCEAN_USER@$DIGITALOCEAN_HOST cd /var/www/api.floreriaenvios.com && pm2 api.floreriaenvios.com || npx pm2 start dist/index.js --name api.floreriaenvios.com"




